version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=quiz_db
      - DB_USERNAME=root
      - DB_PASSWORD=password
    networks:
      - quiz-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  quiz-network:
    driver: bridge
