spring:
  datasource:
    url: jdbc:mariadb://quiz-db.czmygas2kjup.eu-north-1.rds.amazonaws.com:3306/quiz_db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8080
