spring:
  datasource:
    url: quiz-db.czmygas2kjup.eu-north-1.rds.amazonaws.com::3306/quiz_db
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

  server:
    port: 80
