spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:quiz_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

  server:
    port: 8080
